### ISSUE TITLE
Catholicon Recipe cost

### ISSUE THREAD

**Issue by Rogue-Toast** [Rogue-Toast/Raffadax-Complete-Production#18]
Listed as 100,000

**Comment by scriptsforweirdos** [comment]
100000 is accurate as carried over from Raffadax 4.3.0. Changing it is out of scope and needs to go to Raffadax.

See [source](https://github.com/Rogue-Toast/Raffadax-Complete-Production/blob/395384968308d53f72b6b5ce5f14c607f34879db/1.6%20Files/NPCs%20-%20deprecated/%5BSTF%5D%20Raffadax%20Shops/shops.json#L1707C26-L1707C36).
