### ISSUE TITLE
FTM rules with normal Truffles

### ISSUE THREAD

**Issue by Rogue-Toast** [Rogue-Toast/Raffadax-Complete-Production#19]
Added to the pool for artifact dig spots. Look at removing.

**Comment by scriptsforweirdos** [comment]
Again, not added, they were there in the original. [Source](https://github.com/Rogue-Toast/Raffadax-Complete-Production/blob/395384968308d53f72b6b5ce5f14c607f34879db/1.5.6%20Files/%5BFTM%5D%20Forage/content.json#L864)

Changing the content of the original is beyond our scope.
