### ISSUE TITLE
NPC Compatibility broken

### ISSUE THREAD

**Issue by Rogue-Toast** [Rogue-Toast/Raffadax-Complete-Production#22]
- Boarding House NPCs (Boarding House hasn't been updated to 1.6)
- Alecto

**Comment by scriptsforweirdos** [comment]
Game had compat for Boarding House but if it isn't updated we can change the ID for those NPCs to a placeholder for the time being.

Alecto never had gift prefs compat, that's a Raffadax issue. Only SVE and a handful of random other NPCs have compat. No RSV, no Scarp except for Beatrice, no DTZ.

**Comment by Rogue-Toast** [comment]
Alecto has gift prefs compat in the code: https://smapi.io/log/a36bd2c2c3144cb99a4127da58010cdb
