### ISSUE TITLE
Cumin seeds produce cumin seeds

### ISSUE THREAD

**Issue by Rogue-Toast** [Rogue-Toast/Raffadax-Complete-Production#23]
Not sure if this is MYC failing, but I planted 50 cumin seeds and got back 76 cumin seeds of various qualities

**Comment by scriptsforweirdos** [comment]
Not a bug. 

That is intentional. Several crops produce seeds of themselves including Fenugreek, Caraway, Cumin, Black Sesame. This is intended behavior.

**Comment by scriptsforweirdos** [comment]
Reraised by Logo, Cumin yields ONLY cumin seeds, verify.
