### ISSUE TITLE
Forage spawning in places it perhaps shouldn't?

### ISSUE THREAD

**Issue by Rogue-Toast** [Rogue-Toast/Raffadax-Complete-Production#27]
Liverwort - spawned on GI west (where tiger slimes roam)
Blue Oyster Mushroom - spawned on GI west (farm)

**Comment by scriptsforweirdos** [comment]
Those items are in that location in the 1.5.6 source. Not discounting the potential for errors in the source, but I think perhaps this is a case of the spreadsheet being out of date more than the forage being incorrect.

Should I update the spreadsheet to reflect actual locations? Raff can always remove stuff.
