### ISSUE TITLE
Add map compat for Coyote when Aimon's Lively Quarry is installed

### ISSUE THREAD

**Issue by Rogue-Toast** [Rogue-Toast/Raffadax-Complete-Production#29]
Run it by Raff first :)

**Comment by scriptsforweirdos** [comment]
Also map compat for Puck in SVE needs some review.

Via Arrora (Kara):
![image](https://github.com/Rogue-Toast/Raffadax-Complete-Production/assets/22039883/78159782-4adb-41b0-a1b0-70dadf55abae)

**Comment by scriptsforweirdos** [comment]
Mephisto's shop and grimoire do not appear with More Lively Sewer Overhaul.

**Comment by Rogue-Toast** [comment]
They do appear (I'm using it), but per our discussion, I think that there might be hardcoded logic at work since the sewer wasn't unlocked normally. Will have to test on a file where the sewer is still locked to be certain.

**Comment by Rogue-Toast** [comment]
Map compatibility added - now to figure out the visual bug.
