### ISSUE TITLE
Seed costs either equal value of produce or cost more

### ISSUE THREAD

**Issue by Rogue-Toast** [Rogue-Toast/Raffadax-Complete-Production#38]
![image](https://github.com/Rogue-Toast/Raffadax-Complete-Production/assets/142140999/dca64d66-e06a-44f0-a4b7-f169625f8d1c)
![image](https://github.com/Rogue-Toast/Raffadax-Complete-Production/assets/142140999/7cfece98-15b8-4dbf-9e9a-c6315a4bb5eb)
![image](https://github.com/Rogue-Toast/Raffadax-Complete-Production/assets/142140999/cfb485e5-ab06-4073-a133-aa19a679ffdb)
![image](https://github.com/Rogue-Toast/Raffadax-Complete-Production/assets/142140999/3b776c15-4c14-4001-885e-78da2f976cee)

**Comment by scriptsforweirdos** [comment]
You're supposed to be producing things with it. End goal is artisan goods. Price adjustment is a content issue and should be forwarded to Raffadax.
