### ISSUE TITLE
Bug with Macadamia Nut Sapling

### ISSUE THREAD

**Issue by Rogue-Toast** [Rogue-Toast/Raffadax-Complete-Production#52]
I tried to plant it, but it now just sits on the ground. I can't pick it up or move it, but it has collision properties somehow. 

![Mer_5-8-2024_30505956](https://github.com/Rogue-Toast/Raffadax-Complete-Production/assets/142140999/0821dd12-a981-40e6-a952-958721b594fd)
![Mer_5-11-2024_27790105](https://github.com/Rogue-Toast/Raffadax-Complete-Production/assets/142140999/8d5b43da-8d2c-4772-93a5-25c026139378)

**Comment by scriptsforweirdos** [comment]
Could not replicate with a loadout containing only Raffadax + utilities.

**Comment by Rogue-Toast** [comment]
Fixed with https://github.com/Rogue-Toast/Raffadax-Complete-Production/pull/57#issue-2327329904
